sudo: false
language: node_js
node_js:
  - "4"
branches:
  only:
    - master
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune  
script:
  - npm run coverage
  - npm run coverage:check
  - npm run build
after_script:
  - npm run coverage:report